### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pexcn** [pexcn/shadowsocks-heroku#1]
- [ ] use others dockerfiles to enable bbr and tcp fast open ?
- [ ] ~~add obfs plugin ?~~
- [ ] ~~remove `-d 8.8.8.8` params (default is better?) ?~~
- [ ] add option for set dns [?] / add two dns
